<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.js" integrity="sha256-arMsf+3JJK2LoTGqxfnuJPFTU4hAK57MtIPdFpiHXOU=" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </head>
    <body>
    <div class="accordion" id="accordionExample">
        <?php foreach ($expensesByDate as $timestamp => $expenselist) {
        $date = date('d-m-y', $timestamp) ?>
        <div class="card">
            <div class="card-header" id="heading<?php echo $date ?>">
                <h2 class="mb-0">
                    <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse<?php echo $date ?>" aria-expanded="true" aria-controls="collapse<?php echo $date ?>">
                        <?php echo $date ?>
                    </button>
                </h2>
            </div>

            <div id="collapse<?php echo $date ?>" class="collapse" aria-labelledby="heading<?php echo $date ?>" data-parent="#accordionExample">
                <?php foreach ($expenselist as $expense) { ?>
                <div class="card-body">
                    <? echo $expense['expense-name']?>
                    <? echo $expense['expense-value']?>
                    <? echo $expense['category']?>
                    <form method="post" action="/delete-expense" name="delete-expense">
                        <input type="hidden" name="delete-expense" value="<? echo $expense['id']?>">
                        <input type="submit" name="delete-expense" value="X">
                    </form>
                </div>
            <?php }?>
        </div>
        <?php }?>
    </div>
        <?php
        foreach ($monthTotalsByCat as $category => $monthTotal){
            echo 'You spent £'.$monthTotal['monthTotal'].' on '.$category.' since the start of the month <br> <br>';
        }
        ?>
       <?php
        $monthCats = [];
        $monthPercentage = [];
        foreach ($monthTotalsByCat as $category => $monthTotal){
            array_push($monthCats, $category);
            array_push($monthPercentage, $monthTotal['monthPercentage']);
        }
        var_dump($monthTotalExpenditure);
        ?>

        <canvas id="myChart" width="400" height="400"></canvas>
        <script>
            var ctx = document.getElementById('myChart');
            var myChart = new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: <?php echo json_encode($monthCats)?>,
                    datasets: [{
                        label: '# of Votes',
                        data: <?php echo json_encode($monthPercentage)?>,
                        backgroundColor: [
                            'rgba(255, 99, 132, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(255, 206, 86, 0.2)',
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                            'rgba(255, 159, 64, 0.2)'
                        ],
                        borderColor: [
                            'rgba(255, 99, 132, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(255, 159, 64, 1)'
                        ],
                        borderWidth: 1
                    }]
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true
                            }
                        }]
                    }
                }
            });
        </script>

    </body>
</html>
