<?php
$weekCats = [];
$weekPercentage = [];
foreach ($weekTotalsByCat as $category => $weekTotal){
    array_push($weekCats, $category);
    array_push($weekPercentage, $weekTotal['weekPercentage']);
}
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Expenses over the last 7 days</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link href="img/favicon.png" rel="icon">
    <link href="img/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,700|Open+Sans:300,300i,400,400i,700,700i" rel="stylesheet">
    <link href="lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="lib/animate/animate.min.css" rel="stylesheet">
    <link href="lib/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="lib/ionicons/css/ionicons.min.css" rel="stylesheet">
    <link href="lib/magnific-popup/magnific-popup.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet"> </head>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.js" integrity="sha256-qSIshlknROr4J8GMHRlW3fGKrPki733tLq+qeMCR05Q=" crossorigin="anonymous"></script>
<body>
<header id="header">
    <div class="container">
        <div id="title" class="pull-left">
            <h1><a href="/" class="scrollto"><span class="highlight">Expenses Tracker</span></a></h1>
        </div>
        <nav id="nav-menu-container">
            <ul class="nav-menu">
                <li class="menu-active"><a href="/">Home</a></li>
                <li class="menu-has-children"><a href="">View Expenses</a>
                    <ul>
                        <li><a href="/this-month">This month</a></li>
                        <li><a href="/last-7-days">Last 7 days</a></li>
                    </ul>
                </li>
                <li class="menu-has-children" ><a href="">Add Expense</a>
                    <ul>
                        <li>
                            <form method="post" action="/add" class="nav-form">
                                <label for="expense-name" class="form">Expense name:</label>
                                <input type="text" name="expense-name" id="expense-name" required>
                                <label for="expense-value" class="form">Cost of Expense:</label>
                                <input type="number" name="expense-value" id="expense-value" step=".01" required>
                                <label for="date" class="form">Date of Expense:</label>
                                <input type="date" name="date" id="date" required>
                                <label for="category" class="form">Category of Expense:</label>
                                <select name="category" id="category" required>
                                    <option value="Food">Food</option>
                                    <option value="Rent">Rent</option>
                                    <option value="Exercise">Exercise</option>
                                    <option value="Leisure">Leisure</option>
                                </select>
                                <input type="hidden" value="/" name="redirect">
                                <input type="submit" value="Add new expense">
                            </form>
                        </li>
                    </ul>
                </li>
                <li class="menu-has-children" ><a href="">User</a>
                    <ul>
                        <li>
                            <form method="post" action="/update-budget" class="nav-form">
                                <label for="budget" class="form">New monthly budget in £:</label>
                                <input type="number" name="budget" id="budget" required>
                                <input type="hidden" value="<?php echo $userInfo['id'] ?>" name="id">
                                <input type="hidden" value="/last-7-days" name="redirect">
                                <input type="submit" value="Update budget">
                            </form>
                            <form method="post" action="/update-savings-total" class="nav-form">
                                <label for="savings" class="form">Add to or remove from savings:</label>
                                <input type="number" name="savingstotal" id="savings" required>
                                <input type="hidden" value="<?php echo $userInfo['id'] ?>" name="id">
                                <input type="hidden" value="/last-7-days" name="redirect">
                                <input type="submit" value="Update savings total">
                            </form>
                            <form method="post" action="/update-savings-target" class="nav-form">
                                <label for="savingstarget" class="form">Update savings target in £</label>
                                <input type="number" name="savingstarget" id="savings" required>
                                <input type="hidden" value="<?php echo $userInfo['id'] ?>" name="id">
                                <input type="hidden" value="/last-7-days" name="redirect">
                                <input type="submit" value="Update savings target">
                            </form>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</header>
<section id="view" class="section-bg">
    <div class="container-fluid">
        <div class="section-header">
            <h3 class="section-title">Expenses over the last 7 days</h3>
            <div>
                <button id="view-expenses-by-individual">View Expenses by individual date</button>
                <button id="view-expenses-by-chart" class="on">View Chart</button>
            </div>
        </div>

        <div class="row " id="viewchart" >
            <div class="col-lg-8">
                <canvas id="weekChart"></canvas>
                <script>
                    var ctx = document.getElementById('weekChart');
                    var weekChart = new Chart(ctx, {
                        type: 'doughnut',
                        data: {
                            labels: <?php echo json_encode($weekCats)?>,
                            datasets: [{
                                label: '# of Votes',
                                data: <?php echo json_encode($weekPercentage)?>,
                                backgroundColor: [
                                    'rgba(255, 99, 132, 0.2)',
                                    'rgba(54, 162, 235, 0.2)',
                                    'rgba(255, 206, 86, 0.2)',
                                    'rgba(75, 192, 192, 0.2)',
                                    'rgba(153, 102, 255, 0.2)',
                                    'rgba(255, 159, 64, 0.2)'
                                ],
                                borderColor: [
                                    'rgba(255, 99, 132, 1)',
                                    'rgba(54, 162, 235, 1)',
                                    'rgba(255, 206, 86, 1)',
                                    'rgba(75, 192, 192, 1)',
                                    'rgba(153, 102, 255, 1)',
                                    'rgba(255, 159, 64, 1)'
                                ],
                                borderWidth: 1
                            }]
                        },
                        options: {
                            tooltips: {
                                mode: 'label',
                                label: 'mylabel',
                                callbacks: {
                                    label: function (tooltipItem, data) {
                                        var value = Number(data.datasets[0].data[tooltipItem.index]).toFixed(2);
                                        return value+'%';
                                    }, },
                            }
                        }
                    });
                </script>
            </div>
            <div class="col-lg-4 content wow fadeInRight">
                <h2>Over the last 7 days, you've spent:</h2>
                <?php
                foreach ($weekTotalsByCat as $category => $weekTotal){
                    echo '<p><span class="highlight"> £'.$weekTotal['weekTotal'].'</span> on '.$category.'</p>';
                }
                ?>
            </div>
        </div>
        <div class="row" id="viewexpenses">
            <div class="col-lg-12 viewexpenses">
                <div class="viewexpensesbuttons">
                    <?php foreach ($expensesByDate as $timestamp => $expenselist) {
                        $date = date('d-m-y', $timestamp) ?>
                        <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#<?php echo $date ?>" aria-expanded="false" aria-controls="<?php echo $date ?>"><?php echo $date ?></button>
                    <?php } ?>
                </div>
                <?php foreach ($expensesByDate as $timestamp => $expenselist) {
                    $date = date('d-m-y', $timestamp) ?>
                    <div class="row">
                        <div class="col">
                            <div class="collapse multi-collapse" id="<?php echo $date ?>">
                                <?php foreach ($expenselist as $expense) { ?>
                                    <div class="card card-body">
                                        <div class="expense-card">
                                            <p>Expense: <?php echo $expense['expense-name'] ?></p>
                                            <p>Cost: £<?php echo $expense['expense-value'] ?></p>
                                        </div>
                                        <div class="expense-card">
                                            <p>Category: <?php echo $expense['category'] ?></p>
                                            <form method="post" action="/delete" name="delete-expense">
                                                <input type="hidden" name="delete-expense" value="<? echo $expense['id']?>">
                                                <input type="hidden" name="redirect" value="/last-7-days">
                                                <input type="submit" value="Delete">
                                            </form>
                                        </div>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                <?php } ?>
            </div>
        </div>
</section>
<footer>
    <h2>View more of my portfolio at <a href="https://hcoulton.tech"> hcoulton.tech</a></h2>
</footer>
<script src="lib/jquery/jquery.min.js"></script>
<script src="lib/jquery/jquery-migrate.min.js"></script>
<script src="lib/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="lib/easing/easing.min.js"></script>
<script src="lib/wow/wow.min.js"></script>
<script src="lib/superfish/hoverIntent.js"></script>
<script src="lib/superfish/superfish.min.js"></script>
<script src="lib/magnific-popup/magnific-popup.min.js"></script>
<script src="js/main.js"></script>
</body>
</html>
